server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: DonateRaja
    description: A platform for donations, renting, and receiving items.
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://ep-tiny-forest-a17k2xt8.ap-southeast-1.aws.neon.tech:5432/donateraja
    username: donateraja_owner
    password: 9iTbhtqjEkg2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      base64-signing-key: "mXh0/Uotn5+BBVcIzhSxInXDVMXfp7zZPJiXu92WHrA="
      issuer: "donateraja.com"
      access-token-expiration: 1h
      refresh-token-expiration: 7d
    user:
      name: admin
      password: "$2a$10$u8TMYYfe26SOwCoflWiv1.2K2o2qDTiaWm0bttFvXL4Kx4/8aC4YW"  # BCrypt encoded passwordlogging:

logging:
  level:
    org.springframework: INFO
    com.donate.raja.donate_raja: DEBUG  # Adjust log level for your classes
  file:
    name: logs/app.log  # Log to a specific file



jwt:
  secret: "pVLNJbuvCo5tAb/UjHjdbRz+MtNbEfEDS7iuEAtM+IY="  # openssl rand -base64 32
  expiration: 3600000  # Token expiration time in milliseconds (1 hour)



backblaze:
  applicationKeyId: your-application-key-id
  applicationKey: your-application-key
  bucketId: your-bucket-id
  publicBaseUrl: https://f001.backblazeb2.com/file/your-bucket-name
